<?php

namespace Creavo\OptionBundle\Repository;

/**
 * SettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SettingRepository extends \Doctrine\ORM\EntityRepository {

    public function findByName($name) {

        $qb=$this->createQueryBuilder('s');
        $qb
            ->andWhere('s.name = :name')
            ->setParameter('name',$name)
            ->setMaxResults(1);

        return $qb->getQuery()->getOneOrNullResult();
    }

}
